import { Platform, StyleSheet } from "react-native";

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: "#fff" },
    title: { fontSize: 20, fontWeight: "bold", marginBottom: 10 },
    subtitle: { fontSize: 16, marginVertical: 10 },
    price: { fontSize: 18, fontWeight: "bold", marginVertical: 20 },
    customHeader: {
      paddingTop: Platform.OS == "ios" ? 80 : 30,
      paddingBottom: 10,
      backgroundColor: "#fff",
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 10,
      elevation: 4,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    titleContainer: {
      flex: 1,
      alignItems: "center",
    },
    leftIcon: { resizeMode: "contain", width: 25, height: 25 },
    headerTitle: {
      fontSize: 18,
      fontWeight: "500",
      color: "#000",
    },
    headerSubtitle: {
      fontSize: 12,
      color: "#61C3F2",
      marginTop: 5,
      fontWeight: "500",
    },
    seatmap: {
      width: 300,
      height: 200,
      resizeMode: "contain",
      alignSelf: "center",
    },
    bottomContainer: {
      position: "absolute",
      bottom: 40,
      width: "90%",
      alignSelf: "center",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    priceContainer: {
      width: "30%",
      height: 60,
      backgroundColor: "rgba(166,166,166,0.1)",
      borderRadius: 10,
      justifyContent: "center",
      paddingLeft: 10,
    },
    proceedToPay: {
      backgroundColor: "#61C3F2",
      width: "65%",
      borderRadius: 10,
      justifyContent: "center",
      alignItems: "center",
      height: 60,
    },
    proceedToPayText: { color: "#fff", fontWeight: "700", fontSize: 16 },
    priceNumber: { marginTop: 5, fontWeight: "700", fontSize: 16 },
    seatmapContainer: {
      alignSelf: "center",
      backgroundColor: "rgba(166,166,166,0.1)",
      width: "100%",
      height: 400,
      paddingTop: 80,
      marginBottom: 40,
    },
    seatInfoContainer: {
      width: "90%",
      alignSelf: "center",
      flexDirection: "row",
      alignItems: "center",
      marginTop: 15,
    },
    seatImgTextContainer: {
      flexDirection: "row",
      alignItems: "center",
      width: "30%",
    },
    seatImg: { width: 18, height: 18, resizeMode: "contain" },
    seatText: {
      marginLeft: 10,
      color: "#8F8F8F",
      fontSize: 12,
      fontWeight: "500",
    },
    rowContainer: {
      backgroundColor: "rgba(166,166,166,0.1)",
      borderRadius: 10,
      justifyContent: "center",
      width: 100,
      paddingVertical: 10,
      alignItems: "center",
      marginTop: 40,
      marginLeft: "5%",
      flexDirection: "row",
    },
  });